(() => {
'use strict';
const CONFIG={eventDate:'2026-12-05T20:00:00',whatsappNumber:'5513996752376',whatsappMessage:'Olá! Estou confirmando minha presença no XV da Lulu. 💙',pixKey:'13996752376',address:''};
const $=id=>document.getElementById(id),pages={entry:$('entry-page'),invite:$('invite-page'),gifts:$('gifts-page')},toast=$('toast');
let toastTimer,audioContext,oceanNodes=[];
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
function showPage(name){Object.entries(pages).forEach(([key,page])=>{const active=key===name;page.hidden=!active;page.classList.toggle('is-active',active)});window.scrollTo({top:0,behavior:'smooth'})}
function updateCountdown(){const diff=Math.max(0,new Date(CONFIG.eventDate).getTime()-Date.now());$("days").textContent=String(Math.floor(diff/86400000)).padStart(2,'0');$("hours").textContent=String(Math.floor(diff%86400000/3600000)).padStart(2,'0');$("minutes").textContent=String(Math.floor(diff%3600000/60000)).padStart(2,'0');$("seconds").textContent=String(Math.floor(diff%60000/1000)).padStart(2,'0')}
function confirmPresence(){window.open(`https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(CONFIG.whatsappMessage)}`,'_blank','noopener,noreferrer')}
function openLocation(){if(!CONFIG.address.trim()){showToast('O local da festa ainda não foi definido.');return}window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(CONFIG.address)}`,'_blank','noopener,noreferrer')}
async function copyPix(){try{await navigator.clipboard.writeText(CONFIG.pixKey);showToast('Chave Pix copiada! 💙')}catch{showToast(`Pix: ${CONFIG.pixKey}`)}}
function toggleOceanSound(){if(audioContext&&audioContext.state!=='closed'){oceanNodes.forEach(n=>{try{n.stop?.()}catch{}});oceanNodes=[];audioContext.close();audioContext=null;$('btn-sound').textContent='♫';showToast('Som do mar desligado.');return}const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){showToast('Som não disponível neste navegador.');return}audioContext=new Audio();const size=audioContext.sampleRate*2,buffer=audioContext.createBuffer(1,size,audioContext.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<size;i++){last=last*.985+(Math.random()*2-1)*.015;data[i]=last}const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=buffer;source.loop=true;filter.type='lowpass';filter.frequency.value=900;gain.gain.value=.055;source.connect(filter).connect(gain).connect(audioContext.destination);source.start();oceanNodes=[source];$('btn-sound').textContent='◼';showToast('Som do mar ligado. 🌊')}
$('btn-enter').addEventListener('click',()=>showPage('invite'));$('btn-gifts').addEventListener('click',()=>showPage('gifts'));$('btn-back').addEventListener('click',()=>showPage('invite'));$('btn-confirm').addEventListener('click',confirmPresence);$('btn-location').addEventListener('click',openLocation);$('pix-key').addEventListener('click',copyPix);$('btn-sound').addEventListener('click',toggleOceanSound);$('btn-share').addEventListener('click',async()=>{const data={title:'XV da Lulu',text:'Você está convidado(a) para o XV da Lulu! 💙',url:window.location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(window.location.href);showToast('Link copiado!')}}catch{}});
updateCountdown();setInterval(updateCountdown,1000);
if(CONFIG.address.trim()){const button=$('btn-location');button.disabled=false;button.innerHTML='📍 <span>Ver localização</span>'}
})();
